version: '3'
services:

  redis:
    image: redis
    container_name: redis_judge
    ports:
      - 6379:6379

  db:
    image: mysql:5.7
    container_name: mysql_judge
    ports:
      - 3306:3306
environment:
          - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=TheJudge